name: Release

on:
  push:
    tags:
      - 'v*'  # vで始まるタグがプッシュされたときにトリガー

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create ZIP file
        run: |
          zip -r release.zip . -x README.md

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
