name: Deploy

on:
  push:
    branches:
      - 'main'  # mainブランチにプッシュされたときにトリガー

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP file
        run: |
          zip -r release.zip . -x README.md

      - name: Commit and push ZIP file
        run: |
          git config user.name "github-actions"  # GitHub Actionsのユーザー名
          git config user.email "github-actions@github.com"  # GitHub Actionsのメールアドレス
          git add release.zip
          git commit -m "Add release ZIP file"
          git push origin main  # mainブランチにプッシュ
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}  # 組織のトークンを使用
